services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    env_file:
      - hadoop.env
    platform: linux/amd64
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop-namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=${CLUSTER_NAME}
      - CORE_CONF_fs_defaultFS=${CORE_CONF_fs_defaultFS}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 30s
      timeout: 10s
      retries: 3

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    container_name: datanode
    restart: always
    volumes:
      - hadoop-data:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=${CORE_CONF_fs_defaultFS}
    depends_on:
      - namenode

volumes:
  hadoop-data:
  hadoop-namenode:
